name: Supabase Keep Alive

on:
  schedule:
    # Esegue l'azione ogni 3 giorni alle 08:00 UTC
    - cron: '0 8 */3 * *'
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Esegui Ping su Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          psql "$SUPABASE_DB_URL" -c "SELECT * FROM vehicle_types;"
